[project]
name = "ury_pos"
authors = [
    { name = "Quantbit Technologies PVT LTD", email = "support@quantbit.io" }
]
description = "URY POS Application"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
